site_name: pyDreamplet
site_url: https://pydreamplet.github.io
site_description: pyDreamplet is a Python library for SVG manipulation.
site_author: Marek Pilczuk
repo_url: https://github.com/marepilc/pydreamplet
repo_name: marepilc/pydreamplet
nav:
  - index.md
  - Getting started:
    - getting_started/index.md
  - Reference:
    - Core:
      - reference/core/svg.md
      - reference/core/svgelement.md
      - reference/core/transformable.md
      - reference/core/g.md
      - reference/core/animate.md
      - reference/core/circle.md
      - reference/core/ellipse.md
      - reference/core/line.md
      - reference/core/path.md
      - reference/core/rect.md
      - reference/core/text.md
      - reference/core/textonpath.md
    - Shapes:
      - reference/shapes/index.md

    - Math:
      - reference/math/vector.md
    - Noise:
      - reference/noise/noise.md
      - reference/noise/simplex.md
      - reference/noise/simplex2D.md
      - reference/noise/simplex3D.md
    - Colors:
      - reference/colors/index.md
    - Scales:
      - reference/scales/linearscale.md
      - reference/scales/bandscale.md
      - reference/scales/pointscale.md
      - reference/scales/ordinalscale.md
      - reference/scales/colorscale.md
      - reference/scales/squarescale.md
      - reference/scales/circlescale.md
    - Typography:
      - reference/typography/index.md
    - Utils:
      - reference/utils/index.md

  - Blog:
    - blog/index.md
theme:
  name: material
  font: 
    text: "Roboto"
    code: "Roboto Mono"
  logo: "assets/nav_logo.png"
  favicon: "assets/favicon.ico"
  icon:
    repo: material/github
  custom_dir: overrides
  features:
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - content.code.copy
    - search.suggest
  palette:
    # - media: "(prefers-color-scheme)"
    #   toggle:
    #     icon: material/brightness-auto
    #     name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: teal
      accent: orange
    - mediia: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: teal
      accent: orange
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences 
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
plugins:
  - search
  - blog
  # - awesome-pages
extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      analytics: Analytics
    actions:
      - accept
      - manage
  version:
    provider: mike
copyright: >
  Copyright &copy; 2025 Marek Pilczuk —
  <a href="#__consent">Change cookie settings</a>