[project]
name = "pydreamplet"
version = "0.1.0"
description = ""
authors = [
    {name = "Marek Pilczuk",email = "user@mp76.pl"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pillow (>=11.1.0,<12.0.0)",
    "fonttools (>=4.56.0,<5.0.0)",
    "ipython (>=8.32.0,<9.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
jupyter = "^1.1.1"
ruff = "^0.9.5"
pytest = "^8.3.4"

